### ISSUE TITLE
Level Design Third Playable Checklist

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#141]
- [ ] Make a place where the player needs to dash/ is taught to dash
- [ ] Make a place where the player is taught how to drop down from a roof
- [ ] Change collision shape of rocks to better match graphics but also not compromise player movement
- [ ] Ensure that enemy placement does not highlight bugs or catch players by surprise
- [ ] Add tengu to the rooftop level
- [ ] Make sure camera angles do not give players mixed signals or interrupt gameplay
- [ ] Make sure roofs are clearly able to be jumped on or not (in terms of their height relative to inaris jump height)
- [ ] Break up the wall of tutorial text into relevant areas
