### ISSUE TITLE
Game Design Third Playable Checklist

### ISSUE THREAD

**Issue by karenspriggs** [karenspriggs/Inari#142]
- [x] Add heal value to item in inventory
- [x] Set item to automatically use the quick use slot if empty
- [x] Update health and energy UI to match the player's upgraded stats
- [ ] Make pause menu UI not look like default Unity UI
